Repository Arquisoft/dede_en1a, pull requests merged in 2022-03, with the labels that each got.

#35 Created Seller REST
  restapi/api.ts
  restapi/api/SellerREST.ts
  restapi/controllers/SellerController.ts
  restapi/repository/BasicRepository.ts
  restapi/repository/SellerRepository.ts
  restapi/schemas/Seller.ts
  restapi/schemas/SellerSchema.ts
Labels: backend

#41 backend_sellerREST
  restapi/README.md
  restapi/README_es.md
  restapi/api.ts
  restapi/controllers/SellerController.ts
  restapi/interfaces/ProductInterface.ts
  restapi/interfaces/SellerInterface.ts
  restapi/repository/SellerRepository.ts
  restapi/routers/SellerRouter.ts
  restapi/schemas/ProductSchema.ts
  restapi/schemas/Seller.ts
  restapi/schemas/SellerSchema.ts
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/README.md
  webapp/README_es.md
Labels: backend

#42 Backend product crud
  .gitignore
  restapi/controllers/ProductController.ts
  restapi/interfaces/ProductInterface.ts
  restapi/package-lock.json
  restapi/repository/ProductRepository.ts
  restapi/routers/ProductRouter.ts
  restapi/schemas/ProductSchema.ts
  restapi/server.ts
Labels: backend

#54 Solid implementation
  .gitignore
  docs/09_design_decisions.adoc
  docs/package.json
  package-lock.json
  package.json
  restapi/README.md
  restapi/README_es.md
  restapi/api.ts
  restapi/controllers/OrderController.ts
  restapi/controllers/ProductController.ts
  restapi/controllers/SellerController.ts
  restapi/interfaces/OrderInterface.ts
  restapi/interfaces/ProductInterface.ts
  restapi/interfaces/SellerInterface.ts
  restapi/interfaces/UserInterface.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/repository/OrderRepository.ts
  restapi/repository/ProductRepository.ts
  restapi/repository/SellerRepository.ts
  restapi/routers/OrderRouter.ts
  restapi/routers/ProductRouter.ts
  restapi/routers/SellerRouter.ts
  restapi/schemas/OrderSchema.ts
  restapi/schemas/ProductSchema.ts
  restapi/schemas/SellerSchema.ts
  restapi/server.ts
  restapi/solid/solidRouter.ts
  restapi/tests/api.test.ts
  restapi/tests/jest.config.ts
  restapi/tsconfig.json
  webapp/README.md
  webapp/README_es.md
  webapp/server.ts
Labels: backend

#60 List images
  package-lock.json
  package.json
  restapi/package-lock.json
  restapi/package.json
  webapp/package-lock.json
  webapp/public/images/36bc62db0420aa15f0249a94aa6f4609548e06f36857648d6d0b53fe10a9349d.jpg
  webapp/public/images/807fedc1f002afc9dd4aaa34f43d025fbe4a47d7280a342f75ba829261853ae9.jpg
  webapp/public/images/b1cb26b99296eb1a8c3a912987c4a8fb5f99efe66e894d484449fe5fb55a9efb.jpg
  webapp/public/images/logo.png
  webapp/src/components/cart/item/Item.tsx
  webapp/src/components/listProducts/product/CartProduct.tsx
  webapp/src/components/listProducts/product/styles.css
  webapp/src/images/36bc62db0420aa15f0249a94aa6f4609548e06f36857648d6d0b53fe10a9349d.jpg
  webapp/src/images/807fedc1f002afc9dd4aaa34f43d025fbe4a47d7280a342f75ba829261853ae9.jpg
  webapp/src/images/b1cb26b99296eb1a8c3a912987c4a8fb5f99efe66e894d484449fe5fb55a9efb.jpg
Labels: enhancement, frontend

#71 Updated checkout button.
  webapp/src/components/footer/CartFooter.tsx
Labels: frontend

#73 Solid implementation and chechout modification.
  package-lock.json
  package.json
  restapi/package-lock.json
  restapi/server.ts
  restapi/solid/solidRouter.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/api/api.ts
  webapp/src/components/CheckoutDataComponent.tsx
  webapp/src/components/Form.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/LoadingSessionComponent.tsx
  webapp/src/components/LoginButtonComponent.tsx
  webapp/src/components/LogoutButtonComponent.tsx
  webapp/src/components/LogoutSessionComponent.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/footer/CartFooter.tsx
  webapp/src/index.tsx
  webapp/src/pages/DetailsView/DetailsView.tsx
Labels: frontend, backend

#76 Added shipping costs
  restapi/geocoder/geocoder.ts
  webapp/src/components/Order.tsx
  webapp/src/helpers/calculate.ts
Labels: frontend, backend

#78 Deployment
  .github/workflows/asw2122.yml
  docker-compose-deploy.yml
  restapi/server.ts
  restapi/tests/api.test.ts
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/src/App.test.tsx
Labels: enhancement

#79 Factorized .env to asw2122.yml for webapp and restapi
  .github/workflows/asw2122.yml
Labels: deployment

#80 Included arguments and defaults on dockerfile
  restapi/Dockerfile
  restapi/server.ts
Labels: deployment

#81 Refactored localhost calls to include host parameter
  webapp/src/components/login/LoginButtonComponent.tsx
  webapp/src/components/logout/LogoutButtonComponent.tsx
  webapp/src/helpers/getData.ts
  webapp/src/helpers/postData.ts
  webapp/src/pages/DetailsView/DetailsView.tsx
Labels: frontend, deployment

#84 Refactored solid router and multiple addresses are suported.
  restapi/interfaces/ContactDataInterface.ts
  restapi/solid/solidFunctions.ts
  restapi/solid/solidRouter.ts
  webapp/src/components/CheckoutDataComponent.tsx
  webapp/src/components/Form.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/Order.tsx
  webapp/src/components/footer/CartFooter.tsx
Labels: frontend, backend

#87 Implemented dynamic calculation of shipping costs.
  .github/workflows/asw2122.yml
  docs/05_building_block_view.adoc
  docs/07_deployment_view.adoc
  docs/images/DeploymentView_Level1.png
  docs/images/buildingBlock_level1.png
  docs/images/buildingBlock_level2.png
  docs/images/deploymentView_Level1.drawio.png
  restapi/geocoder/geocoder.ts
  restapi/server.ts
  restapi/solid/solidFunctions.ts
  webapp/Dockerfile
  webapp/src/App.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/Sidebar.tsx
  webapp/src/components/cart/item/Item.tsx
  webapp/src/components/cart/item/item-styles.css
  webapp/src/components/checkout/Form.tsx
  webapp/src/components/footer/CartFooter.tsx
  webapp/src/components/footer/styles.css
  webapp/src/components/listProducts/ListProducts.tsx
  webapp/src/components/listProducts/product/CartProduct.tsx
  webapp/src/components/logout/LogoutSessionComponent.tsx
  webapp/src/components/order/Order.tsx
  webapp/src/helpers/getData.ts
  webapp/src/pages/Checkout.tsx
  webapp/src/pages/DetailsView/DetailsView.tsx
  webapp/src/pages/DetailsView/sections/ProductImage.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend, backend

#92 Deployment arguments
  .github/workflows/asw2122.yml
  restapi/server.ts
  webapp/Dockerfile
Labels: deployment

#95 Fixed session in the web.
  restapi/solid/solidFunctions.ts
  webapp/src/components/checkout/Form.tsx
  webapp/src/components/logout/LogoutSessionComponent.tsx
  webapp/src/components/order/Order.tsx
  webapp/src/pages/Checkout.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend, backend
