Repository Arquisoft/dede_en1a, pull requests merged in 2022-04, with the labels that each got.

#103 front end test
  docs/05_building_block_view.adoc
  docs/07_deployment_view.adoc
  webapp/e2e/features/add-to-cart.feature
  webapp/e2e/features/product-details.feature
  webapp/e2e/steps/add-to-cart.steps.ts
  webapp/e2e/steps/product-details.steps.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/_test_/App.test.tsx
  webapp/src/_test_/Calculate.test.tsx
  webapp/src/_test_/Cart.test.tsx
  webapp/src/_test_/CartContext.test.tsx
  webapp/src/_test_/CartFooter.test.tsx
  webapp/src/_test_/CartProduct.test.tsx
  webapp/src/_test_/CartReducer.test.tsx
  webapp/src/_test_/Checkout.test.tsx
  webapp/src/_test_/DetailsView.test.tsx
  webapp/src/_test_/Form.test.tsx
  webapp/src/_test_/Home.test.tsx
  webapp/src/_test_/Item.test.tsx
  webapp/src/_test_/ListProducts.test.tsx
  webapp/src/_test_/LoadingSession.test.tsx
  webapp/src/_test_/LoginButtonComponent.test.tsx
  webapp/src/_test_/LogoutButtonComponent.test.tsx
  webapp/src/_test_/NavBar.test.tsx
  webapp/src/_test_/Navigation.test.tsx
  webapp/src/_test_/Order.test.tsx
  webapp/src/_test_/Sidebar.test.tsx
  webapp/src/_test_/__snapshots__/Cart.test.tsx.snap
  webapp/src/_test_/__snapshots__/CartFooter.test.tsx.snap
  webapp/src/_test_/__snapshots__/CartProduct.test.tsx.snap
  webapp/src/_test_/__snapshots__/Form.test.tsx.snap
  webapp/src/_test_/__snapshots__/Item.test.tsx.snap
  webapp/src/_test_/__snapshots__/ListProducts.test.tsx.snap
  webapp/src/_test_/__snapshots__/NavBar.test.tsx.snap
  webapp/src/_test_/__snapshots__/Sidebar.test.tsx.snap
  webapp/src/components/NavBar.tsx
  webapp/src/components/listProducts/product/CartProduct.tsx
  webapp/src/images/logoName.png
  webapp/src/pages/Checkout.tsx
  webapp/src/pages/DetailsView/DetailsView.tsx
  webapp/src/pages/Home.tsx
Labels: frontend

#105 Dynamic calculation of shipping costs.
  webapp/src/components/checkout/Form.tsx
  webapp/src/components/order/Order.tsx
  webapp/src/helpers/calculate.ts
  webapp/src/pages/Checkout.tsx
Labels: frontend

#108 Documentation delivery3
  docs/01_introduction_and_goals.adoc
  docs/02_architecture_constraints.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/10_quality_scenarios.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/QualityTree.png
  docs/images/buildingBlock_level1.png
  docs/images/buildingBlock_level2.png
  docs/images/business_context_diagram.png
  docs/images/deploymentView_Level1.png
  docs/images/deploymentView_Level1_v2.png
  docs/images/technical_context_diagram.png
  docs/images/uml_domain.png
  docs/package-lock.json
Labels: documentation

#107 Rest test api
  restapi/controllers/SellerController.ts
  restapi/repository/SellerRepository.ts
  restapi/routers/SellerRouter.ts
  restapi/server.ts
  restapi/tests/api.test.ts
Labels: backend, tests

#117 NavBar refactored to material ui
  webapp/src/App.tsx
  webapp/src/_test_/NavBar.test.tsx
  webapp/src/_test_/Navigation.test.tsx
  webapp/src/components/Home.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/login/LoginButtonComponent.tsx
  webapp/src/components/logout/LogoutButtonComponent.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend

#120 finished rest api
  restapi/Dockerfile
  restapi/controllers/OrderController.ts
  restapi/controllers/ProductController.ts
  restapi/controllers/SellerController.ts
  restapi/controllers/helper/hellpers.ts
  restapi/controllers/userController.ts
  restapi/geocoder/geocoder.ts
  restapi/interfaces/ProductInterface.ts
  restapi/interfaces/SellerInterface.ts
  restapi/interfaces/UserInterface.ts
  restapi/repository/OrderRepository.ts
  restapi/repository/ProductRepository.ts
  restapi/repository/SellerRepository.ts
  restapi/routers/OrderRouter.ts
  restapi/routers/ProductRouter.ts
  restapi/routers/SellerRouter.ts
  restapi/routers/geocoderRouter.ts
  restapi/routers/userRouter.ts
  restapi/schemas/ProductSchema.ts
  restapi/schemas/SellerSchema.ts
  restapi/schemas/UserSchema.ts
  restapi/server.ts
  restapi/solid/solidFunctions.ts
  restapi/tests/api.test.ts
Labels: backend

#124 Created page to select pod provider.
  webapp/src/_test_/LoginButtonComponent.test.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/userAuthentication/LogInSignUpComponent.tsx
  webapp/src/components/userAuthentication/SelectProviderComponent.tsx
  webapp/src/components/userAuthentication/loginLogogut/LoginButtonComponent.tsx
  webapp/src/components/userAuthentication/loginLogogut/LoginSolid.tsx
  webapp/src/components/userAuthentication/loginLogogut/SignUpButtonComponent.tsx
Labels: frontend

#126 user add fixed
  restapi/controllers/userController.ts
Labels: backend

#128 Ci tests
  .github/workflows/asw2122.yml
  restapi/package-lock.json
  restapi/package.json
  restapi/tests/api.test.ts
  restapi/tests/test-db-handler.ts
  restapi/tsconfig.json
  webapp/src/_test_/LoadingSession.test.tsx
  webapp/src/_test_/LoginButtonComponent.test.tsx
  webapp/src/_test_/Order.test.tsx
  webapp/src/_test_/__snapshots__/CartFooter.test.tsx.snap
  webapp/src/_test_/__snapshots__/CartProduct.test.tsx.snap
  webapp/src/_test_/__snapshots__/Form.test.tsx.snap
  webapp/src/_test_/__snapshots__/Item.test.tsx.snap
  webapp/src/_test_/__snapshots__/NavBar.test.tsx.snap
Labels: deployment, tests

#137 Use jwt
  restapi/controllers/ProductController.ts
  restapi/middleware/checkJWT.ts
  restapi/middleware/checkRole.ts
  restapi/middleware/checkSeller.ts
  restapi/package-lock.json
  restapi/package.json
  restapi/routers/OrderRouter.ts
  restapi/routers/ProductRouter.ts
  restapi/routers/userRouter.ts
  restapi/server.ts
  webapp/auth/generateToken.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
Labels: frontend, backend

#139 Product filtration
  webapp/src/components/listProducts/ListProducts.tsx
Labels: frontend

#132 Checkout refactoring
  restapi/solid/solidCommunityFetch.ts
  restapi/solid/solidInruptFetch.ts
  restapi/solid/solidRouter.ts
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/_test_/Cart.test.tsx
  webapp/src/_test_/CartFooter.test.tsx
  webapp/src/_test_/Navigation.test.tsx
  webapp/src/_test_/Sidebar.test.tsx
  webapp/src/components/NavBar.tsx
  webapp/src/components/Navigation.tsx
  webapp/src/components/Sidebar.tsx
  webapp/src/components/cart/Cart.tsx
  webapp/src/components/cart/item/Item.tsx
  webapp/src/components/cartFooter/CartFooter.tsx
  webapp/src/components/checkout/CheckoutSuccessComponent.tsx
  webapp/src/components/checkout/DisplayOrderSummaryComponent.tsx
  webapp/src/components/checkout/DisplayProductsComponent.tsx
  webapp/src/components/checkout/DisplayShippingDataComponent.tsx
  webapp/src/components/checkout/Form.tsx
  webapp/src/components/checkout/HorizontalLinearStepper.tsx
  webapp/src/components/userAuthentication/SelectProviderComponent.tsx
  webapp/src/components/userAuthentication/loginLogogut/LoginButtonComponent.tsx
  webapp/src/components/userAuthentication/loginLogogut/LoginSolid.tsx
  webapp/src/components/userAuthentication/loginLogogut/LogoutButtonComponent.tsx
  webapp/src/helpers/validateProviderUrl.ts
  webapp/src/hooks/usePodData.tsx
  webapp/src/hooks/useShipping.tsx
  webapp/src/shared/shareddtypes.ts
Labels: frontend

#146 Deployment workbench
  .github/workflows/asw2122.yml
  docker-compose-deploy.yml
  docker-compose.yml
  webapp/package-lock.json
  webapp/package.json
  webapp/src/_test_/__snapshots__/NavBar.test.tsx.snap
Labels: enhancement, deployment
