Repository Arquisoft/dede_en1a, pull requests merged in 2022-05, with the labels that each got.

#158 Deployment workbench
  .github/workflows/asw2122.yml
  restapi/Dockerfile
  restapi/tests/api.test.ts
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/src/_test_/App.test.tsx
  webapp/src/_test_/Checkout.test.tsx
  webapp/src/_test_/Form.test.tsx
  webapp/src/_test_/Home.test.tsx
  webapp/src/_test_/Item.test.tsx
  webapp/src/_test_/NavBar.test.tsx
  webapp/src/_test_/Navigation.test.tsx
  webapp/src/_test_/__snapshots__/CartProduct.test.tsx.snap
  webapp/src/_test_/__snapshots__/Item.test.tsx.snap
  webapp/src/_test_/__snapshots__/NavBar.test.tsx.snap
Labels: deployment

#163 Cors config
  .github/workflows/asw2122.yml
  restapi/server.ts
  restapi/solid/solidCommunityFetch.ts
Labels: backend

#165 tests snapshot cart
  webapp/src/_test_/__snapshots__/CartProduct.test.tsx.snap
Labels: frontend, tests

#164 Final tweaks
  docs/01_introduction_and_goals.adoc
  docs/04_solution_strategy.adoc
  docs/05_building_block_view.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/08_concepts.adoc
  docs/11_technical_risks.adoc
  docs/12_glossary.adoc
  docs/images/deploymentView_Level1.png
  webapp/public/favicon.ico
  webapp/public/images/logo.png
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/src/components/NavBar.tsx
  webapp/src/components/footer/Footer.tsx
  webapp/src/components/userAuthentication/SelectProviderComponent.tsx
  webapp/src/images/logo.png
Labels: documentation, frontend

#166 Fixed solid and frontend things
  restapi/solid/solidFetch.ts
  restapi/solid/solidInruptFetch.ts
  restapi/solid/solidRouter.ts
  webapp/src/components/Sidebar.tsx
  webapp/src/components/cart/Cart.tsx
  webapp/src/components/cartFooter/CartFooter.tsx
  webapp/src/components/solid/SolidNameComponent.tsx
  webapp/src/helpers/validateProviderUrl.ts
  webapp/src/hooks/usePodData.tsx
Labels: frontend, backend

#167 added more information
  docs/08_concepts.adoc
  docs/09_design_decisions.adoc
  docs/11_technical_risks.adoc
Labels: documentation

#169 Select provider sign up tweaks.
  webapp/src/components/userAuthentication/SelectProviderComponent.tsx
Labels: frontend

#172 Run prod
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
Labels: frontend, deployment

#173 Docs update 4
  docs/01_introduction_and_goals.adoc
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
Labels: documentation

#177 process.env.REACT_APP_API_URI set
  webapp/src/hooks/usePodData.tsx
Labels: bug, frontend, deployment

#180 process.env.REACT_APP_API_URI set again on other files
  webapp/src/components/checkout/Form.tsx
  webapp/src/hooks/useShipping.tsx
  webapp/src/pages/Checkout.tsx
Labels: bug

#185 Fixing restapi url in shipping
  webapp/src/hooks/useShipping.tsx
Labels: frontend

#184 Fixing restapi url in shipping
  webapp/src/hooks/useShipping.tsx
Labels: frontend
